dryRun: true

logLevel: debug
logFormat: console

source:
  # Filters provide control over what pods will be processed.
  # By default all pods will be processed. If a condition matches, the pod will NOT be processed.
  # For query language details see https://jmespath.org/
  filters:
    - jmespath: "obj.metadata.namespace == 'kube-system'"

#  registries:
#    dockerio:
#      username:
#      password:

target:
  type: aws
  registry:
    aws:
      accountId: ***REMOVED***
      region: ap-southeast-2
      ecrOptions:
        tags: []
        imageTagMutability: MUTABLE
        imageScanningConfiguration:
          imageScanOnPush: true
        encryptionConfiguration:
          encryptionType: AES256
#          kmsKey: string
#    dockerio:
#    quayio:
