apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name:  {{ template "k8s-image-swapper.fullname" . }}
  labels:
    {{- include "k8s-image-swapper.labels" . | nindent 4 }}
webhooks:
  - name: k8s-image-swapper.github.io
    {{- if .Values.patch.enabled  }}
    failurePolicy: Ignore
    {{- else }}
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    {{- end }}
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        resources:
          - deployments
          - daemonsets
          - cronjobs
          - jobs
          - statefulsets
          - pods
        operations:
          - CREATE
          - UPDATE
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ template "k8s-image-swapper.fullname" $ }}
        path: /webhook
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
